name: Android APK Olusturucu

on:
  push:
    branches: [ "ana" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu Cek
      uses: actions/checkout@v4

    - name: Java 17 Kur
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Gradle'i Kur
      uses: gradle/actions/setup-gradle@v4

    - name: Calistirma Izni Ver
      run: chmod +x gradlew

    - name: APK Hazirla
      run: ./gradlew assembleDebug

    - name: APK Dosyasini Yukle
      uses: actions/upload-artifact@v4
      with:
        name: VPN-Uygulamasi
        path: app/build/outputs/apk/debug/*.apk
