name: VPN APK Olusturucu

on:
  push:
    branches: [ "Main", "Ana", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Kodu Cek
      uses: actions/checkout@v4
    
    - name: Java 17 Kur
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle Ortamini Hazirla
      uses: gradle/actions/setup-gradle@v4

    - name: APK Hazirla
      run: chmod +x gradlew && ./gradlew assembleDebug

    - name: APK Dosyasini Yukle
      uses: actions/upload-artifact@v4
      with:
        name: VPN-Uygulamam
        path: app/build/outputs/apk/debug/app-debug.apk
