name: VPN APK Olusturucu

on:
  push:
    branches: [ "Ana", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Kodu Cek
      uses: actions/checkout@v4
    
    - name: Java 17 Kur
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle Kur ve APK Hazirla
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: assembleDebug
